version: "3.9"

services:
  # operator services
  operator:
    build:
      context: ..
      dockerfile: ./Dockerfile
    image: operator
    container_name: operator
    restart: always
    volumes:
      - ..:/app
      - ./database:/database
      - $KEYSTORES_PATH:/keystores
      - $KEYSTORES_PASSWORD_PATH:/keystores/password.txt
      - $DEPOSIT_DATA_PATH:/deposit_data.json
    env_file:
      - .env
    entrypoint: [ "python" ]
    command: [ "./src/main.py" ]
    environment:
      KEYSTORES_PATH: /keystores
      KEYSTORES_PASSWORD_PATH: /keystores/password.txt
      DEPOSIT_DATA_PATH: /deposit_data.json
      DATABASE: /database/operator.db
